[book]
title = "Rust Embedded MB2 Discovery Book"
description = "Discover the world of microcontrollers through Rust with the micro:bit v2 (MB2)"
authors = ["Rust Embedded Resources Team"]
language = "en"

[output.html]
git-repository-url = "https://github.com/rust-embedded/discovery-mb2/"
additional-js = ["epub-link.js"]

# ensures visibility of transparent svg or png images
additional-css = ["theme/css/custom.css"]

[output.epub]
# Optional settings
title = "Rust Embedded MB2 Discovery Book"
author = "Rust Embedded Resources Team"

[output.html.site]
url = "/"
# Optional settings
# base-url = "/discovery-mb2/"
# git-repository-url = "

