[package]
name = "inputs-and-polling"
version = "0.1.0"
edition = "2021"

[dependencies]
microbit-v2 = "0.15.0"
cortex-m-rt = "0.7.3"
rtt-target = "0.5.0"
panic-rtt-target = "0.1.3"

[dependencies.cortex-m]
version = "0.7"
features = ["critical-section-single-core"]
